### ISSUE TITLE
Erro ao rodar nova versão

### ISSUE THREAD

**Issue by lucianowayand** [ColmeiaUDESC/site-colmeia#18]
![image](https://user-images.githubusercontent.com/36968613/124283992-ec9cc480-db22-11eb-86bf-7d6ebb187a5e.png)

acabei dando merge sem testar na máquina local, alguém sabe resolver?

**Comment by lucianowayand** [comment]
Ao trocar o host no database.yml para localhost foi solucionado, tem a ver com o docker?

**Comment by joaodematte** [comment]
sim, o host do postgresql quando se usa docker é o mesmo que a imagem do docker está usando, no docker.compose.yml tem o seguinte código:
```
postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
```

na primeira linha se define o nome da imagem (que será o nome do host), e acho que no database.yml não tava setado pra "postgres", acho que tava pra "db" (ou a configuração no docker-compose.yml estava invertida), mas acredito que já tenha sido resolvido com o pr que eu fiz do docker.
